### ISSUE TITLE
Problem med länkning av PDF

### ISSUE THREAD

**Issue by bastian94** [devscoutsweden/aktivitetsbanken-android#109]
Det är problem med läkningar till externa PDF dokument. Appen tolkat det som en webb adress och öpnnar chrome och sedan så skickas jag till en adress med PDF dokument som namn och så blir det problem med att öppna det.

**Comment by mikaelsvensson** [comment]
Kan du ge ett exempel på en aktivitet med PDF-länk?

**Comment by bastian94** [comment]
Hittar inte längre någon aktivitet där den länkar en pdf. Hittar massa aktiviterter med hännvisningar till pdf dokument på webben men inga av dessa är klickbara

**Comment by mikaelsvensson** [comment]
Chiffer-aktiviteten verkar ha PDF-länkar, och andra länker också för den delen. Inga fungerar i appen.
