### ISSUE TITLE
Problem med Google inlogging

### ISSUE THREAD

**Issue by bastian94** [devscoutsweden/aktivitetsbanken-android#97]
När man stänger av appen och startar om den så är man utloggad i alla fall grafiskt ifrån google( Alltså att man måste trycka på logga in på start skärmen) När jag tittar under inställningar så står det logga ut och ta bort kopplingen mot google.

**Comment by mikaelsvensson** [comment]
Syns alltid utloggningsalternativet i inställningsmenyn eller syns det bara när du är inloggad enligt startsidan?

**Comment by mikaelsvensson** [comment]
Ja, man måste aktivt logga in varje gång appen startas. Gör man det via menyn måste man göra om auktoriseringen (godkänna appen) vid nästa inloggning men loggar man ut på startsidan behöver man bara välja konto.

Det skulle vara enkelt att låta appen logga in per automatik eftersom man bara behöver spara undan användarens kontoinformation (användarens gmail-adress).

**Comment by bastian94** [comment]
Ja utloggnings alternativet syns alltid i inställningarna. och ja jag tror det är en bra ide att låta appen autologga in när den släpps officiellt

**Comment by mikaelsvensson** [comment]
Att göra:
* Skapa inställning för att alltid logga in (dvs. spara användarens gmail-adress och automatiskt logga in varje gång appen startas). Inställningen (kryssruta) ska vara ikryssad från början.
* Dölj utloggningsalternativet från inställningsmenyn när användaren inte är inloggad.
